#
#. This config file adds support for Netlify CMS, exposed at /admin on the running site.
# In order to use this on your site,
#. 1) replace instances of "exampleSite/......" with the appropriate paths, relative from repository root.
#. 2) replace repo path in `backend` settings, and set branch to master.
#  3) Optionally enable the [editor workflow](https://www.netlifycms.org/docs/configuration-options/#publish-mode) which uses PRs for content changes
#  4) Optionally enable [open authoring](https://www.netlifycms.org/docs/open-authoring/) for community sites, which requires #3
#  
#
locale: 'de'


backend:
  name: git-gateway
  # repo: grasgruenit/devweb
  branch: main


media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
  - label: "Inhalt"
    name: "inhalt"
    files: 
      - label: "Home"
        name: "home"
        file: "/content/home.md"
        fields: # The fields each document in this collection have
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "TCM"
        name: "tcm"
        file: "/content/tcm.md"
        fields: # The fields each document in this collection have
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Reihenfolge", name: "weight", widget: "number"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Psycho"
        name: "psycho"
        file: "/content/psycho.md"
        fields: # The fields each document in this collection have
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Reihenfolge", name: "weight", widget: "number"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Praxis"
        name: "praxis"
        file: "/content/praxis.md"
        fields: # The fields each document in this collection have
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Reihenfolge", name: "weight", widget: "number"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Uebermich"
        name: "uebermich"
        file: "/content/uebermich.md"
        fields: # The fields each document in this collection have
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Reihenfolge", name: "weight", widget: "number"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Kontakt"
        name: "kontakt"
        file: "/content/kontakt.md"
        fields: # The fields each document in this collection have
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Reihenfolge", name: "weight", widget: "number"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
       
